### ISSUE TITLE
Nothing works when I click "I don't have a Redis database" under RedisInsight

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/redisinsight-docker-extension#1]
Once the extension is up and running, if you try to go to Docker dashboard > Extensions > Click on "I don't have a Redis database" nothing works.

Here's the steps to reproduce:
- Clone the repository
- Change directory to redisinsight-docker-extension
- make build-extension
- docker extension install <name of extension>

**Comment by collabnix** [comment]
closing this as the new interfaces doesn't have that option available.
