### ISSUE TITLE
Why are the internal extension containers publishing their ports?

### ISSUE THREAD

**Issue by floge07** [collabnix/redisinsight-docker-extension#12]
![image](https://github.com/collabnix/redisinsight-docker-extension/assets/53813973/66693782-cf84-49f0-9744-eafe8bf3a9ff)

This is a bit annoying since I now can't run my actual Redis container on the default port 6379. Is this necessary?

**Comment by ajeetraina** [comment]
Hi @floge07 I have modified Redis port to be exposed at 6381 instead of 6379.
I hope that helps.

**Comment by floge07** [comment]
@ajeetraina Yes, that prevents my problem. Thank you!

**Comment by AleksandrTaranzhin** [comment]
》¿¤°`~•

**Comment by AleksandrTaranzhin** [comment]
@ajeetraina
