### ISSUE TITLE
Build UI

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/redisinsight-docker-extension#4]
It's always recommended to build UI rather than just embedding the tool into the Extension. 
Is there a possibility to modify some basic components like buttons to comply with the Docker style guide?

**Comment by collabnix** [comment]
Let's target Redis Stack. It comes with RedisInsight v2.0 which is the latest version.

Refer: https://redis.io/docs/stack/get-started/install/docker/

**Comment by gagandeepp** [comment]
@collabnix  @ajeetraina Can you please explain which approach to take?

**Comment by ajeetraina** [comment]
Hi @gagandeepp Can you run the below Docker command on your laptop:

```
 docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
```

and then once it comes up, browse to https://localhost:8001

Let me know if it works for you.

**Comment by gagandeepp** [comment]
> 

![image](https://user-images.githubusercontent.com/34858937/195610783-0f72b093-edb5-48df-ae0c-cfa04d0c8090.png)

**Comment by ajeetraina** [comment]
Perfect. This is v2.x of RedisInsight.

The one which we have now is v1.x , so we need to upgrade it first.

Next, we need to build UI rather than mounting the extension UI.

**Comment by gagandeepp** [comment]
lets connect on slack @ajeetraina

**Comment by collabnix** [comment]
@gagandeepp Can you please update README.md file with the latest screenshots.

**Comment by gagandeepp** [comment]
@ajeetraina is this completed?

**Comment by ajeetraina** [comment]
Yes, that's completed.

**Comment by gagandeepp** [comment]
Okay let’s jump on slack tomorrow to get more details
